name: tanghit
description: tanghit app
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^1.0.1
  cupertino_icons: ^0.1.2
  firebase_database:
  url_launcher: ^5.4.1
  share: ^0.6.3+5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/first.jpg
    - assets/images/second.jpg
    - assets/images/third.jpg
