version: 2
jobs:
  build:    
    macos:
      xcode: "11.4.0"
    steps:
      - checkout

      - run:
          name: download flutter SDK
          command: |
            if ! test -f "flutter_sdk.zip"; then 
              git clone https://github.com/flutter/flutter.git -b stable
            fi
            export PATH="$PATH:`pwd`/flutter/bin"
            flutter doctor
          
      - run:
          name: Run Flutter doctor
          command: cd ..; flutter doctor

      - run: flutter pub get
      - run: flutter build aot -t "lib/main.dart"
      - run: flutter test --no-pub
      - run: flutter analyze --no-pub
      - run: flutter format . --set-exit-if-changed --fix
 
      - run:
          name: Build the Android version
          command: flutter build apk 

      - store_artifacts:
          path: build/app/outputs/apk/release/app-release.apk