version: 2
jobs:
  build:    
    docker:
      - image: cirrusci/flutter:v1.12.13 

    steps:
      - checkout

      - run:
          name: Run Flutter doctor
          command: flutter doctor

      - run: flutter pub get
      - run: flutter build aot -t "lib/main.dart"
      - run: flutter test --no-pub
      - run: flutter analyze --no-pub
      - run: flutter format . --set-exit-if-changed --fix
 
      - run:
          name: Build the Android version
          command: flutter build apk 

      - store_artifacts:
          path: build/app/outputs/apk/release/app-release.apk