on: push
jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        platform: [ios, aot, apk, web]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build ${{ matrix.platform }} -t "lib/main.dart"
      - run: flutter test --no-pub
      - run: flutter analyze --no-pub
      - run: flutter format . --set-exit-if-changed --fix
