on: push
jobs:
  test:
    name: Test on ${{ matrix.platform }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build aot -t "lib/main.dart"
      - run: flutter test --no-pub
      - run: flutter analyze --no-pub
      - run: flutter format . --set-exit-if-changed --fix
 
  test_ios:
    name: Test on iOS
    runs-on: macos-latest
    needs: test
    strategy:
      matrix:
        device:
            - "iPhone 8"
            - "iPhone 11 Pro Max"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter pub get
      - run: xcrun instruments -s
      - run: open -a Simulator
      - run: xcrun simctl boot "${{ matrix.device }}"
      - run: flutter test --no-pub
      - run: flutter run

  # test_android:
  #   name: Test on Android
  #   runs-on: macos-latest
  #   needs: test
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-java@v1
  #       with:
  #         java-version: '12.x'
  #     - uses: subosito/flutter-action@v1
  #       with:
  #         channel: 'beta'
  #     - run: flutter pub get
  #     - run: open -a Simulator
  #     - run: xcrun simctl boot "${{ matrix.device }}"
  #     - run: flutter test --no-pub
  #     - run: flutter run
      
  # test_web:
  #   name: Test on Web
  #   runs-on: macos-latest
  #   needs: test
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-java@v1
  #       with:
  #         java-version: '12.x'
  #     - uses: subosito/flutter-action@v1
  #       with:
  #         channel: 'beta'
  #     - run: flutter pub get
  #     - run: flutter build web
